version: "3.9"

services:
  db: 
    container_name: db-f8
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default
    ports:
      - "5000:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  